name = "astro-worker"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true

# D1データベースの設定
[[d1_databases]]
binding = "DB"
database_name = "lifelog"
database_id = "4409121c-e368-4ff6-8d42-44e5ac95658a"

[vars]
PUBLIC_API_BASE_URL = "https://portfolio.bianchiidentity.workers.dev"
